spring:
  application:
    name: vintage-hub-be
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

vintage-hub:
  admin:
    password-hash-api-enabled: ${VINTAGE_HUB_ADMIN_PASSWORD_HASH_API_ENABLED:false}
  jwt:
    secret: ${VINTAGE_HUB_JWT_SECRET:}
    access-token-validity-seconds: ${VINTAGE_HUB_JWT_ACCESS_TOKEN_VALIDITY_SECONDS:1800}
